# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"logger": "03_calc.ipynb",
         "TEF_object": "00_tef_core.ipynb",
         "calc_volume_transport": "03_calc.ipynb",
         "calc_salt_transport": "03_calc.ipynb",
         "sort_1dim": "03_calc.ipynb",
         "sort_2dim": "03_calc.ipynb",
         "calc_bulk_values": "03_calc.ipynb"}

modules = ["tef_core.py",
           "calc.py"]

doc_url = "https://florianboergel.github.io/TotalExchangeFlow/"

git_url = "https://github.com/florianboergel/TotalExchangeFlow/tree/master/"

def custom_doc_links(name): return None
