# AUTOGENERATED! DO NOT EDIT! File to edit: 04_download_test_data.ipynb (unless otherwise specified).

__all__ = ['download_test_data']

# Cell
# Code from xarray
try:
    import pooch
except ImportError as e:
    raise ImportError(
        "tutorial.download_test_data depends on pooch to download and manage datasets."
        " To proceed please install pooch."
    ) from e

# Cell
def download_test_data(downloadpath):
    filepath_1d_winter = pooch.retrieve("https://github.com/florianboergel/pyTEF/raw/master/data/SoH_2_2011_01.nc",
                                    known_hash=None, path = downloadpath, fname = "SoH_2_2011_01.nc")
    filepath_1d_summer = pooch.retrieve("https://github.com/florianboergel/pyTEF/raw/master/data/SoH_2_2011_08.nc",
                                    known_hash=None, path = downloadpath, fname = "SoH_2_2011_08.nc")
    filepath_2d_winter = pooch.retrieve("https://github.com/florianboergel/pyTEF/raw/master/data/Surface_2011_01.nc",
                                    known_hash=None,  path = downloadpath, fname = "Surface_2011_01.nc")
    filepath_2d_summer = pooch.retrieve("https://github.com/florianboergel/pyTEF/raw/master/data/Surface_2011_08.nc",
                                    known_hash=None,  path = downloadpath, fname = "Surface_2011_08.nc")
