# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"logger": "00_tef_core.ipynb",
         "TEF_object": "00_tef_core.ipynb"}

modules = ["tef_core.py"]

doc_url = "https://florianboergel.github.io/tef/"

git_url = "https://github.com/florianboergel/tef/tree/master/"

def custom_doc_links(name): return None
